version: "3"

services: 
  nameservice:
    build:
      context: ./
    ports:
      - "1317:1317"
      - "26656-26657:26656-26657"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "./init.sh"
